/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import UserTypes.*;
import RoomTypes.*;
import Util.EmergencyMode;
import Util.Log;
import Util.UniAccessSystem;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;

/**
 *
 * @author odmoa
 */
public class SystemUi extends javax.swing.JFrame {

    /**
     * Creates new form SystemUi
     */
    public SystemUi() {
        initComponents();
    }
    
    private static UniAccessSystem system;

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabs = new javax.swing.JTabbedPane();
        RoomsTab = new javax.swing.JSplitPane();
        RoomsScrollPane = new javax.swing.JScrollPane();
        RoomsTable = new javax.swing.JTable();
        RoomsButtonsScrollPane = new javax.swing.JScrollPane();
        RoomsButtonsPanel = new javax.swing.JPanel();
        SetEmergencyModeRoomCodeTextField = new javax.swing.JTextField();
        SetToNormalBtn = new javax.swing.JButton();
        SetToEmergencyBtn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        CreateRoomCodeTextField = new javax.swing.JTextField();
        CreateRoomTypeComboBox = new javax.swing.JComboBox<>();
        CreateRoomBtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        RemoveRoomCodeTextField = new javax.swing.JTextField();
        RemoveRoomBtn = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        CampusToNormalBtn = new javax.swing.JButton();
        CampusToEmergencyBtn = new javax.swing.JButton();
        UsersTab = new javax.swing.JSplitPane();
        UsersScrollPane = new javax.swing.JScrollPane();
        UsersTable = new javax.swing.JTable();
        UsersButtonsScrollPane = new javax.swing.JScrollPane();
        UsersButtonsPanel = new javax.swing.JPanel();
        CreateUserFirstNameTextField = new javax.swing.JTextField();
        CreateUserLastNameTextField = new javax.swing.JTextField();
        CreateUserTypeComboBox = new javax.swing.JComboBox<>();
        CreateUserBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        ModifyUserIdTextField = new javax.swing.JTextField();
        ModifyUserFirstNameTextField = new javax.swing.JTextField();
        ModifyUserLastNameTextField = new javax.swing.JTextField();
        ModifyUserTypeComboBox = new javax.swing.JComboBox<>();
        ModifyUserBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        RemoveUserIdTextField = new javax.swing.JTextField();
        RemoveUserBtn = new javax.swing.JButton();
        LogsTab = new javax.swing.JSplitPane();
        LogsScrollPane = new javax.swing.JScrollPane();
        logTextPane = new javax.swing.JTextPane();
        LogsButtonsScrollPane = new javax.swing.JScrollPane();
        LogsButtonsPanel = new javax.swing.JPanel();
        SaveLogBtn = new javax.swing.JButton();
        RefreshLogBtn = new javax.swing.JButton();
        SimulationTab = new javax.swing.JPanel();
        simulationUserIdTextField = new javax.swing.JTextField();
        simulationRoomCodeTextField = new javax.swing.JTextField();
        simulateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        MainTabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainTabsMouseClicked(evt);
            }
        });

        RoomsTab.setResizeWeight(1.0);

        RoomsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RoomsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        RoomsTable.setAutoCreateRowSorter(true);
        RoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Code", "Access Type", "Emergency Mode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RoomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomsTableMouseClicked(evt);
            }
        });
        RoomsScrollPane.setViewportView(RoomsTable);

        RoomsTab.setTopComponent(RoomsScrollPane);

        RoomsButtonsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RoomsButtonsScrollPane.setHorizontalScrollBar(null);
        RoomsButtonsScrollPane.setMinimumSize(new java.awt.Dimension(170, 6));

        RoomsButtonsPanel.setMinimumSize(new java.awt.Dimension(120, 6));

        SetEmergencyModeRoomCodeTextField.setText("Room Code");
        SetEmergencyModeRoomCodeTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        SetEmergencyModeRoomCodeTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        SetToNormalBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SetToNormalBtn.setText("Set To Normal");
        SetToNormalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetToNormalBtnActionPerformed(evt);
            }
        });

        SetToEmergencyBtn.setBackground(new java.awt.Color(255, 51, 51));
        SetToEmergencyBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SetToEmergencyBtn.setForeground(new java.awt.Color(255, 255, 255));
        SetToEmergencyBtn.setText("Set To EMERGENCY");
        SetToEmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetToEmergencyBtnActionPerformed(evt);
            }
        });

        jSeparator5.setMinimumSize(new java.awt.Dimension(120, 6));
        jSeparator5.setPreferredSize(new java.awt.Dimension(100, 25));

        CreateRoomCodeTextField.setText("Room Code");
        CreateRoomCodeTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateRoomCodeTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        CreateRoomTypeComboBox.setModel(new DefaultComboBoxModel(RoomType.values()));
        CreateRoomTypeComboBox.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateRoomTypeComboBox.setPreferredSize(new java.awt.Dimension(100, 25));
        CreateRoomTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRoomTypeComboBoxActionPerformed(evt);
            }
        });

        CreateRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CreateRoomBtn.setText("Create Room");
        CreateRoomBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateRoomBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        CreateRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRoomBtnActionPerformed(evt);
            }
        });

        jSeparator6.setMinimumSize(new java.awt.Dimension(120, 6));
        jSeparator6.setPreferredSize(new java.awt.Dimension(100, 25));

        RemoveRoomCodeTextField.setText("Room Code");
        RemoveRoomCodeTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        RemoveRoomCodeTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        RemoveRoomBtn.setBackground(new java.awt.Color(255, 51, 51));
        RemoveRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RemoveRoomBtn.setForeground(new java.awt.Color(255, 255, 255));
        RemoveRoomBtn.setText("Remove Room");
        RemoveRoomBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        RemoveRoomBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        RemoveRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveRoomBtnActionPerformed(evt);
            }
        });

        jSeparator7.setMinimumSize(new java.awt.Dimension(120, 6));
        jSeparator7.setPreferredSize(new java.awt.Dimension(100, 25));

        CampusToNormalBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CampusToNormalBtn.setText("Set Campus To Normal");
        CampusToNormalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampusToNormalBtnActionPerformed(evt);
            }
        });

        CampusToEmergencyBtn.setBackground(new java.awt.Color(255, 51, 51));
        CampusToEmergencyBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CampusToEmergencyBtn.setForeground(new java.awt.Color(255, 255, 255));
        CampusToEmergencyBtn.setText("Campus EMERGENCY");
        CampusToEmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampusToEmergencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoomsButtonsPanelLayout = new javax.swing.GroupLayout(RoomsButtonsPanel);
        RoomsButtonsPanel.setLayout(RoomsButtonsPanelLayout);
        RoomsButtonsPanelLayout.setHorizontalGroup(
            RoomsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateRoomCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateRoomTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveRoomCodeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SetToEmergencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SetToNormalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SetEmergencyModeRoomCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampusToEmergencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampusToNormalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(RoomsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RoomsButtonsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        RoomsButtonsPanelLayout.setVerticalGroup(
            RoomsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SetEmergencyModeRoomCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetToNormalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetToEmergencyBtn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateRoomCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateRoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(RemoveRoomCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampusToNormalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampusToEmergencyBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RoomsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomsButtonsPanelLayout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(243, 243, 243)))
        );

        RoomsButtonsScrollPane.setViewportView(RoomsButtonsPanel);

        RoomsTab.setRightComponent(RoomsButtonsScrollPane);

        MainTabs.addTab("Rooms", RoomsTab);

        UsersTab.setResizeWeight(1.0);

        UsersScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        UsersScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        UsersScrollPane.setMinimumSize(new java.awt.Dimension(200, 6));

        UsersTable.setAutoCreateRowSorter(true);
        UsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UsersTable.setToolTipText("");
        UsersTable.setAutoscrolls(false);
        UsersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersTableMouseClicked(evt);
            }
        });
        UsersScrollPane.setViewportView(UsersTable);

        UsersTab.setTopComponent(UsersScrollPane);

        UsersButtonsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        UsersButtonsScrollPane.setHorizontalScrollBar(null);
        UsersButtonsScrollPane.setMinimumSize(new java.awt.Dimension(170, 6));

        UsersButtonsPanel.setMinimumSize(new java.awt.Dimension(120, 6));

        CreateUserFirstNameTextField.setText("First Name");
        CreateUserFirstNameTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateUserFirstNameTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        CreateUserLastNameTextField.setText("Last Name");
        CreateUserLastNameTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateUserLastNameTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        CreateUserTypeComboBox.setModel(new DefaultComboBoxModel(UserType.values()));
        CreateUserTypeComboBox.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateUserTypeComboBox.setPreferredSize(new java.awt.Dimension(100, 25));
        CreateUserTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserTypeComboBoxActionPerformed(evt);
            }
        });

        CreateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CreateUserBtn.setText("Create User");
        CreateUserBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        CreateUserBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        CreateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserBtnActionPerformed(evt);
            }
        });

        jSeparator3.setMinimumSize(new java.awt.Dimension(120, 6));
        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 25));

        ModifyUserIdTextField.setText("User ID");
        ModifyUserIdTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        ModifyUserIdTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        ModifyUserFirstNameTextField.setText("New First Name");
        ModifyUserFirstNameTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        ModifyUserFirstNameTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        ModifyUserLastNameTextField.setText("New Last Name");
        ModifyUserLastNameTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        ModifyUserLastNameTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        ModifyUserTypeComboBox.setModel(new DefaultComboBoxModel(UserType.values()));
        ModifyUserTypeComboBox.setMinimumSize(new java.awt.Dimension(120, 6));
        ModifyUserTypeComboBox.setPreferredSize(new java.awt.Dimension(100, 25));
        ModifyUserTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyUserTypeComboBoxActionPerformed(evt);
            }
        });

        ModifyUserBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModifyUserBtn.setText("Modify User");
        ModifyUserBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        ModifyUserBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        ModifyUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyUserBtnActionPerformed(evt);
            }
        });

        jSeparator4.setMinimumSize(new java.awt.Dimension(120, 6));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 25));

        RemoveUserIdTextField.setText("User ID");
        RemoveUserIdTextField.setMinimumSize(new java.awt.Dimension(120, 6));
        RemoveUserIdTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        RemoveUserBtn.setBackground(new java.awt.Color(255, 51, 51));
        RemoveUserBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RemoveUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        RemoveUserBtn.setText("Remove User");
        RemoveUserBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        RemoveUserBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        RemoveUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsersButtonsPanelLayout = new javax.swing.GroupLayout(UsersButtonsPanel);
        UsersButtonsPanel.setLayout(UsersButtonsPanelLayout);
        UsersButtonsPanelLayout.setHorizontalGroup(
            UsersButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsersButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateUserTypeComboBox, 0, 148, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateUserLastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateUserFirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyUserIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyUserFirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyUserLastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyUserTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveUserIdTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        UsersButtonsPanelLayout.setVerticalGroup(
            UsersButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateUserTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyUserIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModifyUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyUserTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveUserIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UsersButtonsScrollPane.setViewportView(UsersButtonsPanel);

        UsersTab.setRightComponent(UsersButtonsScrollPane);

        MainTabs.addTab("Users", UsersTab);

        LogsTab.setResizeWeight(1.0);

        LogsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        LogsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        logTextPane.setEditable(false);
        LogsScrollPane.setViewportView(logTextPane);

        LogsTab.setTopComponent(LogsScrollPane);

        LogsButtonsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        LogsButtonsScrollPane.setHorizontalScrollBar(null);
        LogsButtonsScrollPane.setMinimumSize(new java.awt.Dimension(170, 6));

        LogsButtonsPanel.setMinimumSize(new java.awt.Dimension(120, 6));

        SaveLogBtn.setText("Save Log");
        SaveLogBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        SaveLogBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        SaveLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveLogBtnActionPerformed(evt);
            }
        });

        RefreshLogBtn.setText("REFRSH LOG");
        RefreshLogBtn.setMinimumSize(new java.awt.Dimension(120, 6));
        RefreshLogBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        RefreshLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshLogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogsButtonsPanelLayout = new javax.swing.GroupLayout(LogsButtonsPanel);
        LogsButtonsPanel.setLayout(LogsButtonsPanelLayout);
        LogsButtonsPanelLayout.setHorizontalGroup(
            LogsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogsButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(RefreshLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        LogsButtonsPanelLayout.setVerticalGroup(
            LogsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogsButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveLogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshLogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogsButtonsScrollPane.setViewportView(LogsButtonsPanel);

        LogsTab.setRightComponent(LogsButtonsScrollPane);

        MainTabs.addTab("Logs", LogsTab);

        simulationUserIdTextField.setText("User Id");

        simulationRoomCodeTextField.setText("Room Code");

        simulateBtn.setText("SIMULATE!");
        simulateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SimulationTabLayout = new javax.swing.GroupLayout(SimulationTab);
        SimulationTab.setLayout(SimulationTabLayout);
        SimulationTabLayout.setHorizontalGroup(
            SimulationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulationTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SimulationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simulationRoomCodeTextField)
                    .addComponent(simulationUserIdTextField)
                    .addComponent(simulateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap(628, Short.MAX_VALUE))
        );
        SimulationTabLayout.setVerticalGroup(
            SimulationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SimulationTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulationUserIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simulationRoomCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simulateBtn)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        MainTabs.addTab("Simulation", SimulationTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        MainTabs.getAccessibleContext().setAccessibleName("Users");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserBtnActionPerformed
        
        User newUser = new User() {};
        newUser.SetName(CreateUserFirstNameTextField.getText() + " " + CreateUserLastNameTextField.getText());
        newUser.SetUserType((UserType)CreateUserTypeComboBox.getSelectedItem());        
        system.userList.CreateUser(newUser);        
        RefreshUserTable();
    }//GEN-LAST:event_CreateUserBtnActionPerformed

    private void SaveLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveLogBtnActionPerformed
        try {
            Log.GetInstance().Save();
        } catch (IOException ex) {
            Logger.getLogger(SystemUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveLogBtnActionPerformed

    private void simulateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateBtnActionPerformed
        
        if(system.userList.UserExists(Integer.parseInt(simulationUserIdTextField.getText()))){          
            if(system.roomList.RoomExists(simulationRoomCodeTextField.getText())){
                if(system.userList.FindUserById(Integer.parseInt(simulationUserIdTextField.getText()
                )).AttemptAccess(system.roomList.FindRoom(simulationRoomCodeTextField.getText()))){
                    ShowMessage("Access Granted!");
                }
                else{
                    ShowIssue("Access Denied.");
                }
            }
            else{
                ShowIssue("Cannot find room!");
            }
        }
        else{
            ShowIssue("Cannot find user!");
        }
    }//GEN-LAST:event_simulateBtnActionPerformed

    private void ModifyUserTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyUserTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyUserTypeComboBoxActionPerformed

    private void CreateUserTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateUserTypeComboBoxActionPerformed

    private void ModifyUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyUserBtnActionPerformed

        int modId = Integer.parseInt(ModifyUserIdTextField.getText());
        User modUser = system.userList.FindUserById(modId);
        if(modUser != null){
            
            String modName = ModifyUserFirstNameTextField.getText() + " " + ModifyUserLastNameTextField.getText();
            UserType modType = (UserType)ModifyUserTypeComboBox.getSelectedItem();
            
            modUser.SetName(modName);
            modUser.SetUserType(modType);
            
            system.userList.SetUser(modId, modUser);
            RefreshUserTable();
        }
        else{
            ShowIssue("Cannot find user!");
        }
    }//GEN-LAST:event_ModifyUserBtnActionPerformed

    private void RemoveUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserBtnActionPerformed
    
        int removeId = Integer.parseInt(RemoveUserIdTextField.getText());
        User removeUser = system.userList.FindUserById(removeId);
        if(removeUser != null){
            
            ShowMessage("User " + removeUser.GetId() + " (" + removeUser.GetName() + ", " + removeUser.GetUserType() + "),\nhas been removed.");
            
            system.userList.RemoveUser(removeId);            
            RefreshUserTable();
        }
        else{
            ShowIssue("Cannot find user!");
        }
    }//GEN-LAST:event_RemoveUserBtnActionPerformed

    private void UsersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersTableMouseClicked
        
        int row = UsersTable.getSelectedRow();
        String userId = UsersTable.getModel().getValueAt(row, 0).toString();
        String userWholeName = UsersTable.getModel().getValueAt(row, 1).toString();
        String[] userSplitName = userWholeName.split("\\s+");
        ModifyUserIdTextField.setText(userId);
        simulationUserIdTextField.setText(userId);
        ModifyUserFirstNameTextField.setText(userSplitName[0]);
        if(userSplitName.length > 1){
            ModifyUserLastNameTextField.setText(userSplitName[1]);
        }
        else{
            ModifyUserLastNameTextField.setText("");
        }
        
        RemoveUserIdTextField.setText(userId);
    }//GEN-LAST:event_UsersTableMouseClicked

    private void CreateRoomTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRoomTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateRoomTypeComboBoxActionPerformed

    private void CreateRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRoomBtnActionPerformed
        String roomCode = CreateRoomCodeTextField.getText();
        if(!system.roomList.RoomExists(roomCode)){
            Room newRoom = new Room() {};
        newRoom.SetCode(roomCode);
        newRoom.SetRoomType((RoomType)CreateRoomTypeComboBox.getSelectedItem());        
        system.roomList.CreateRoom(newRoom);        
        RefreshRoomTable();
        }
        else{
            ShowIssue(roomCode + " already exists!");
        }
    }//GEN-LAST:event_CreateRoomBtnActionPerformed

    private void RemoveRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveRoomBtnActionPerformed
        String removeCode = RemoveRoomCodeTextField.getText();
        Room removeRoom = system.roomList.FindRoom(removeCode);
        if(removeRoom != null){
            
            ShowMessage(removeRoom.GetRoomType() + " " + removeRoom.GetCode() + "\nhas been removed.");
            
            system.roomList.RemoveRoom(removeCode);
            RefreshUserTable();
        }
        else{
            ShowIssue("Cannot find room!");
        }
    }//GEN-LAST:event_RemoveRoomBtnActionPerformed

    private void SetToEmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetToEmergencyBtnActionPerformed
        String roomCode = SetEmergencyModeRoomCodeTextField.getText();
        Room room = system.roomList.FindRoom(roomCode);
        if(room != null){
            room.SetEmergencyMode(EmergencyMode.Emergency);        
            RefreshRoomTable();
            
            System.out.println("Set room " + room.GetCode() + " to " + room.GetEmergencyMode());
        }
        else{
            ShowIssue("Cannot find room '" + roomCode + "'!");
        }
    }//GEN-LAST:event_SetToEmergencyBtnActionPerformed

    private void SetToNormalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetToNormalBtnActionPerformed
        
        String roomCode = SetEmergencyModeRoomCodeTextField.getText();
        Room room = system.roomList.FindRoom(roomCode);
        if(room != null){
            room.SetEmergencyMode(EmergencyMode.Normal);
            RefreshRoomTable();
            
            System.out.println("Set room " + room.GetCode() + " to " + room.GetEmergencyMode());
        }
        else{
            ShowIssue("Cannot find room '" + roomCode + "'!");
        }
    }//GEN-LAST:event_SetToNormalBtnActionPerformed

    private void RoomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsTableMouseClicked

        int row = RoomsTable.getSelectedRow();
        String roomCode = RoomsTable.getModel().getValueAt(row, 0).toString();
        
        SetEmergencyModeRoomCodeTextField.setText(roomCode);
        CreateRoomCodeTextField.setText(roomCode);
        RemoveRoomCodeTextField.setText(roomCode);
        simulationRoomCodeTextField.setText(roomCode);
    }//GEN-LAST:event_RoomsTableMouseClicked

    private void CampusToEmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampusToEmergencyBtnActionPerformed
        try {        
            system.SetCampusMode(EmergencyMode.Emergency);
        } catch (IOException ex) {
            Logger.getLogger(SystemUi.class.getName()).log(Level.SEVERE, null, ex);
        }
        RefreshRoomTable();
    }//GEN-LAST:event_CampusToEmergencyBtnActionPerformed

    private void CampusToNormalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampusToNormalBtnActionPerformed
        try {        
            system.SetCampusMode(EmergencyMode.Normal);
        } catch (IOException ex) {
            Logger.getLogger(SystemUi.class.getName()).log(Level.SEVERE, null, ex);
        }
        RefreshRoomTable();
    }//GEN-LAST:event_CampusToNormalBtnActionPerformed

    private void RefreshLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshLogBtnActionPerformed
        
        logTextPane.setText(Log.GetInstance().GetLogString());
    }//GEN-LAST:event_RefreshLogBtnActionPerformed

    private void MainTabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainTabsMouseClicked
        logTextPane.setText(Log.GetInstance().GetLogString());
    }//GEN-LAST:event_MainTabsMouseClicked

    private void ShowMessage(String message){
        JFrame frame = new JFrame("Message");
            JOptionPane.showMessageDialog(frame, message);
    }
    
    private void ShowIssue(String issue){
        JFrame frame = new JFrame("Issue");
            JOptionPane.showMessageDialog(frame, issue);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new SystemUi().setVisible(true);

            system = new UniAccessSystem();

            system.userList.CreateUser("Jeff");
            system.userList.CreateUser("Ron");
            system.userList.CreateUser("Jane");
            system.userList.CreateUser("Rosetta");
            system.userList.CreateUser("Keith");
            
            system.roomList.CreateRoom("BGB201", RoomType.StudentLab);
            system.roomList.CreateRoom("BGB202", RoomType.LectureHall);
            system.roomList.CreateRoom("BGB203", RoomType.ResearchLab);
            system.roomList.CreateRoom("BGB204", RoomType.StaffRoom);
            system.roomList.CreateRoom("BGB205", RoomType.SecureRoom);
        
            RefreshUserTable();
            RefreshRoomTable();
            }
        });
    }
    
    public static void RefreshRoomTable(){
        
        DefaultTableModel model = (DefaultTableModel) RoomsTable.getModel();
        model.setRowCount(0);
        
        for(int i = 0; i < system.roomList.GetRooms().size(); i++){
            
            Room room = system.roomList.GetRooms().get(i);
            String codeFieldData = room.GetCode();
            String typeFieldData = room.GetRoomType().toString();
            String modeFieldData = room.GetEmergencyMode().toString();
            
            model.addRow(new Object[]{codeFieldData, typeFieldData, modeFieldData});
        }
        
        RoomsTable.setModel(model);
    }
    
    public static void RefreshUserTable(){
        
        DefaultTableModel model = (DefaultTableModel) UsersTable.getModel();        
        model.setRowCount(0);
        
        for(int i = 0; i < system.userList.GetUsers().size(); i++){
            
            User user = system.userList.GetUsers().get(i);
            int idFieldData = user.GetId();
            String nameFieldData = user.GetName();
            String typeFieldData = user.GetUserType().toString();
            model.addRow(new Object[]{idFieldData, nameFieldData, typeFieldData});
        }
        
        UsersTable.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CampusToEmergencyBtn;
    private javax.swing.JButton CampusToNormalBtn;
    private javax.swing.JButton CreateRoomBtn;
    private javax.swing.JTextField CreateRoomCodeTextField;
    private javax.swing.JComboBox<String> CreateRoomTypeComboBox;
    private javax.swing.JButton CreateUserBtn;
    private javax.swing.JTextField CreateUserFirstNameTextField;
    private javax.swing.JTextField CreateUserLastNameTextField;
    private javax.swing.JComboBox<UserType> CreateUserTypeComboBox;
    private javax.swing.JPanel LogsButtonsPanel;
    private javax.swing.JScrollPane LogsButtonsScrollPane;
    private javax.swing.JScrollPane LogsScrollPane;
    private javax.swing.JSplitPane LogsTab;
    private javax.swing.JTabbedPane MainTabs;
    private javax.swing.JButton ModifyUserBtn;
    private javax.swing.JTextField ModifyUserFirstNameTextField;
    private javax.swing.JTextField ModifyUserIdTextField;
    private javax.swing.JTextField ModifyUserLastNameTextField;
    private javax.swing.JComboBox<String> ModifyUserTypeComboBox;
    private javax.swing.JButton RefreshLogBtn;
    private javax.swing.JButton RemoveRoomBtn;
    private javax.swing.JTextField RemoveRoomCodeTextField;
    private javax.swing.JButton RemoveUserBtn;
    private javax.swing.JTextField RemoveUserIdTextField;
    private javax.swing.JPanel RoomsButtonsPanel;
    private javax.swing.JScrollPane RoomsButtonsScrollPane;
    private javax.swing.JScrollPane RoomsScrollPane;
    private static javax.swing.JSplitPane RoomsTab;
    private static javax.swing.JTable RoomsTable;
    private javax.swing.JButton SaveLogBtn;
    private javax.swing.JTextField SetEmergencyModeRoomCodeTextField;
    private javax.swing.JButton SetToEmergencyBtn;
    private javax.swing.JButton SetToNormalBtn;
    private javax.swing.JPanel SimulationTab;
    private javax.swing.JPanel UsersButtonsPanel;
    private javax.swing.JScrollPane UsersButtonsScrollPane;
    private javax.swing.JScrollPane UsersScrollPane;
    private javax.swing.JSplitPane UsersTab;
    private static javax.swing.JTable UsersTable;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextPane logTextPane;
    private javax.swing.JButton simulateBtn;
    private javax.swing.JTextField simulationRoomCodeTextField;
    private javax.swing.JTextField simulationUserIdTextField;
    // End of variables declaration//GEN-END:variables
}
